### ISSUE TITLE
Update loopyloop to latest version

### ISSUE THREAD

**Issue by jacoscaz** [gultar/blockchain#1]
Hello! I am the author of `loopyloop`, a module that shows up amongst `blockchain`'s dependencies. I just wanted to give you a heads-up as I've released a new major version of `loopyloop`. Nothing has changed API-wise but I've dropped all external dependencies, removed support for Node.js versions  `< 8.0.0` and updated all dev dependencies to their latest versions.

**Comment by gultar** [comment]
Alright! Thanks for the update. It's a nice, useful package, by the way, thanks again!
